image: node:latest

stages:
  - build

variables:
  CACHE_PATH: node_modules/

build:
  stage: build
  before_script:
    - cd candidate_service
  script:
    - npm install
  artifacts:
    paths:
      - node_modules
  cache:
    key: ${CACHE_PATH}-${CI_COMMIT_REF_SLUG}
    paths:
      - ${CACHE_PATH}

